#ifndef __KSU_UAPI_SELINUX_H
#define __KSU_UAPI_SELINUX_H

#include <linux/types.h>
 
#ifdef __BINDGEN__
#define DECLARE(type, name, val) static const type name = val
#else
#define DECLARE(type, name, val) enum { name = val }
#endif 

DECLARE(__u32, KSU_SEPOLICY_CMD_NORMAL_PERM, 1);
DECLARE(__u32, KSU_SEPOLICY_CMD_XPERM, 2);
DECLARE(__u32, KSU_SEPOLICY_CMD_TYPE_STATE, 3);
DECLARE(__u32, KSU_SEPOLICY_CMD_TYPE, 4);
DECLARE(__u32, KSU_SEPOLICY_CMD_TYPE_ATTR, 5);
DECLARE(__u32, KSU_SEPOLICY_CMD_ATTR, 6);
DECLARE(__u32, KSU_SEPOLICY_CMD_TYPE_TRANSITION, 7);
DECLARE(__u32, KSU_SEPOLICY_CMD_TYPE_CHANGE, 8);
DECLARE(__u32, KSU_SEPOLICY_CMD_GENFSCON, 9);

DECLARE(__u32, KSU_SEPOLICY_SUBCMD_NORMAL_PERM_ALLOW, 1);
DECLARE(__u32, KSU_SEPOLICY_SUBCMD_NORMAL_PERM_DENY, 2);
DECLARE(__u32, KSU_SEPOLICY_SUBCMD_NORMAL_PERM_AUDITALLOW, 3);
DECLARE(__u32, KSU_SEPOLICY_SUBCMD_NORMAL_PERM_DONTAUDIT, 4);

DECLARE(__u32, KSU_SEPOLICY_SUBCMD_XPERM_ALLOW, 1);
DECLARE(__u32, KSU_SEPOLICY_SUBCMD_XPERM_AUDITALLOW, 2);
DECLARE(__u32, KSU_SEPOLICY_SUBCMD_XPERM_DONTAUDIT, 3);

DECLARE(__u32, KSU_SEPOLICY_SUBCMD_TYPE_STATE_PERMISSIVE, 1);
DECLARE(__u32, KSU_SEPOLICY_SUBCMD_TYPE_STATE_ENFORCE, 2);

DECLARE(__u32, KSU_SEPOLICY_SUBCMD_TYPE_CHANGE_CHANGE, 1);
DECLARE(__u32, KSU_SEPOLICY_SUBCMD_TYPE_CHANGE_MEMBER, 2);

#endif
