name: Build Kernel

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: America/Sao_Paulo
      KBUILD_BUILD_USER: Leo
      KBUILD_BUILD_HOST: android-build

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0 # Penting agar Git bisa melakukan operasi commit
          
      - name: Apply Specific Commit
        run: |
          # Mengambil commit dari repository rd-stuffs
          curl -Ls https://github.com/rinnsakaguchi/android_kernel_common-5.10/commit/fd14e9907b49ccc7a7a94c17d0489c8d47f4c8c0
          
      - name: Build
        run: |
          bash build.sh
          bash build.sh --su

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: kernel-zips
          path: "*.zip"

      - name: Send to Telegram
        run: |
          DATE=$(date '+%H:%M %d/%m/%Y')
          COMMIT="https://github.com/${{ github.repository }}/commit/$(git rev-parse HEAD)"
          STANDARD=$(ls Void-Project-surya-*.zip)
          KSU=$(ls Void-Project-KSU-*.zip)
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
            -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -F document=@"${STANDARD}" \
            -F caption="${DATE}"$'\n\n'"${COMMIT}"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
            -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -F document=@"${KSU}"
