name: Release Prebuilt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: America/Sao_Paulo
      KBUILD_BUILD_USER: nobody
      KBUILD_BUILD_HOST: android-build

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Configure git
        run: |
          git config --global user.name "Richard Raya"
          git config --global user.email "rdxzv.dev@gmail.com"

      - name: Setup commit-msg hook
        run: |
          mkdir -p ~/.git/hooks
          git config --global core.hooksPath ~/.git/hooks
          curl -fsSL https://gist.githubusercontent.com/UtsavBalar1231/c48cb6993ff45b077d41c13622fc27ba/raw/66f7da7f128a9511df81d624f23f87fc294b59b6/commit-msg \
            -o ~/.git/hooks/commit-msg
          chmod +x ~/.git/hooks/commit-msg

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PREBUILT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Build
        run: bash build.sh

      - name: Export prebuilts
        run: bash prebuilt.sh --release
